# Generated by Django 4.1.5 on 2023-08-09 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('accepted', models.BooleanField(default=False)),
                ('userAcceptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userAcceptor', to=settings.AUTH_USER_MODEL)),
                ('userRequestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userRequestor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
