# Generated by Django 4.2.4 on 2023-08-31 15:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0002_friendrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='insertionDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 31, 15, 39, 5, 619390, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='accepted',
            field=models.SmallIntegerField(),
        ),
    ]
